
name: Launch EC2 Instance & s3 bucket creation

on:
  workflow_dispatch:

jobs:
  launch-ec2:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ var.AWS_REGION }}  # Change to your preferred region

      - name: Launch EC2 instance
        run: |
          aws ec2 run-instances \
            --image-id ami-084568db4383264d4 \  # Replace with a valid AMI ID
            --count 1 \
            --instance-type t2.micro \
            --key-name github-action-key-pair \  # Replace with your key pair name
            --security-groups default
