
name: Launch EC2 Instance & S3 Bucket Creation

on:
  workflow_dispatch:

jobs:
  launch-ec2:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}  # Use secrets or hardcode region

      - name: Create Ec2 Instance
        run: |
          aws ec2 run-instances \
            --image-id ami-084568db4383264d4 \
            --count 1 \
            --instance-type t2.micro \
            --key-name github-action-key-pair \
            --security-groups default
