name: Create and Auto-Terminate EC2 Instance (Manual Input)

on:
  workflow_dispatch:
    inputs:
      ami_id:
        description: 'AMI ID'
        required: true
        default: 'ami-084568db4383264d4'
      instance_type:
        description: 'Instance Type'
        required: true
        default: 't2.micro'
      key_name:
        description: 'Key Pair Name'
        required: true
        default: 'github-action-key-pair'
      security_group:
        description: 'Security Group Name'
        required: true
        default: 'default'

jobs:
  ec2-lifecycle:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Launch EC2 instance
        id: launch
        run: |
          INSTANCE_ID=$(aws ec2 run-instances \
            --image-id ${{ github.event.inputs.ami_id }} \
            --count 1 \
            --instance-type ${{ github.event.inputs.instance_type }} \
            --key-name ${{ github.event.inputs.key_name }} \
            --security-groups ${{ github.event.inputs.security_group }} \
            --query 'Instances[0].InstanceId' \
            --output text)
          echo "INSTANCE_ID=$INSTANCE_ID" >> $GITHUB_ENV
          echo "Launched instance ID: $INSTANCE_ID"

      - name: Wait for instance to be running
        run: |
          aws ec2 wait instance-running --instance-ids ${{ env.INSTANCE_ID }}
          echo "Instance ${{ env.INSTANCE_ID }} is now running."

      - name: Simulate usage (optional)
        run: |
          echo "Simulating instance usage..."
          sleep 60

      - name: Terminate EC2 instance
        run: |
          aws ec2 terminate-instances --instance-ids ${{ env.INSTANCE_ID }}
          aws ec2 wait instance-terminated --instance-ids ${{ env.INSTANCE_ID }}
          echo "Instance ${{ env.INSTANCE_ID }} terminated."
